version: '3.4'

services:
  curso-restful:
    image: curso-restful
    build:
      context: .
      dockerfile: curso-restful/Dockerfile    
    ports:
      - "5000:80"    
    networks:
      - rede

  db:
    image: postgres
    container_name: "db"
    environment:
      - POSTGRES_DB=testedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=GMT        
    volumes:
      - "/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    networks:
      - rede

networks:
  rede:
    driver: bridge